title: 北京佳膜
company: 北京佳膜
enCompany: Beijing Giamor
tel: 010-67722766
tel2: 400-850-5815
address: 北京市丰台区大溪地二区二号楼105
email: postmaster@giamor-tech.com
com_detail: <p></p>
collections:
 about:
   name: 关于我们
   output: true
 en_product:
   name: english
   output: true
 product:
   name: 核心产品
   output: true
 en_about:
   name: 
   output: true
baseurl: "" # the subpath of your site, e.g. /blog 
imgurl: ""
#port:    4000
#host:    192.168.88.101
