title: 北京加膜
company: 北京加膜
tel: 
address: 
com_detail: <p></p>
collections:
 about:
   name: 关于我们
   output: true
 en_product:
   name: english
   output: true
 product:
   name: 核心产品
   output: true
 en_about:
   name: 
   output: true
baseurl: "" # the subpath of your site, e.g. /blog 
imgurl: ""
#port:    4000
#host:    192.168.88.101
