title: 北京佳膜
company: 北京佳膜
enCompany: Beijing Giamor
tel: +86 186 1189 8868
tel2: +86 185 0103 7265
tel_zuoji: +86(0)10 86229818 
address: 北京市丰台区大溪地二区二号楼105
email: l.zhang@giamor-tech.com
email2: mabelzhang21@gmail.com
com_detail: <p></p>
collections:
 about:
   name: 关于我们
   output: true
 en_product:
   name: english
   output: true
 product:
   name: 核心产品
   output: true
 en_about:
   name: 
   output: true
baseurl: "" # the subpath of your site, e.g. /blog 
imgurl: "http://img.xindapin.cn/jiamo/"
#port:    4000
#host:    192.168.88.101
